spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: tobelthenewone38@gmail.com
    password: jyopavkhbljqousd
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          starttls:
            enable: false
        debug: true

  datasource:
    url: jdbc:h2:file:./data/healthcaredb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: "a_very_long_random_secret_key_string_here_123456_i_thought_of_a_random_string_but_it_can_be_anything_as_long_as_it_is_secure_and_not_easily_guessable_you_should_change_this_in_production_please_make_it_secure_and_long_enough_to_prevent_brute_force_attacks"
  expiration: 86400000 # 24 hours in milliseconds

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG
